# 배포 작업
deploy-to-server:
    stage: deploy
    only:
        - master
    script:
        - echo 'DEPLOY RUNNING'
        - npm install --progress=false
        - npm run build
        - pwd
        - firebase deploy

    tags:
        - deploy
        
# 빌드 테스트 작업
build-test:
    stage: build
    script:
        - echo 'BUILD TEST RUNNING'
        - npm install --progress=false
        - npm run build
    tags:
        - build
