# 배포 작업
deploy-to-server:
    stage: deploy
    only:
        - master
    script:
        - echo 'hello world'
    tags:
        - deploy
        
# 빌드 테스트 작업
build-from-develop:
    stage: build
    script:
        - echo 'BUILD TEST RUNNING!'
    tags:
        - build
        

# 머지 작업
merge-to-develop:
    stage: test
    only:
        - merge_requests
    script:
        - echo 'MERGE'
    tags:
        - merge