# 배포 작업
deploy-to-server:
    stage: deploy
    only:
        - master
    script:
        - echo 'DEPLOY RUNNING'
        - cd client
        - npm install --progress=false
        - npm run build
        - cd ../server
        - npm install --progress=false
        - chmod 700 runserver.sh
        - ./runserver.sh
    tags:
        - deploy
        
# 빌드 테스트 작업
build-test:
    stage: build
    script:
        - echo 'BUILD TEST RUNNING'
        - cd client
        - npm install --progress=false
        - npm run build
    tags:
        - build
